apiVersion: apps/v1
kind: Deployment
metadata:
  name: drools-workbench-custom-deployment
spec:
  selector:
    matchLabels:
      run: drools-workbench-custom
  replicas: 1
  template:
    metadata:
      labels:
        run: drools-workbench-custom
    spec:
      containers:
        - name: drools-workbench-custom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 8080
          - containerPort: 8001
