apiVersion: v1
kind: Service
metadata:
  name: drools-workbench-custom-service
  labels:
    run: drools-workbench-custom
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: proxy
  selector:
    run: drools-workbench-custom
